name: Github Actions Demo
run-name: ${{ github.actor }} is testing out Gihub Actions
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by Github!"
      - run: echo "The name of your branch is ${{ github.ref }} and you repository is ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@4
      - run: echp "The ${{ github.repository }} has been cloned"
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: echp "This job's status is ${{ job.status }}"
